# Generated by Django 4.0.4 on 2022-05-07 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, verbose_name='Comment text')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('parent_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.comment', verbose_name='Parent comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=200, verbose_name='Post header')),
                ('content', models.JSONField(verbose_name='Post content')),
                ('number_of_views', models.SmallIntegerField(default=0, verbose_name='Post number of views')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='Update at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.BooleanField(verbose_name='Like or dislike')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('author_ip', models.GenericIPAddressField(verbose_name='Author ip address')),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.comment', verbose_name='Reaction on comment')),
                ('post', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.post', verbose_name='Reaction on post')),
            ],
            options={
                'verbose_name': 'Reaction',
                'verbose_name_plural': 'Reactions',
            },
        ),
        migrations.CreateModel(
            name='PostTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.post', verbose_name='Tag for post')),
                ('tag_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.tag', verbose_name='Value tag for post')),
            ],
            options={
                'verbose_name': 'Post tag',
                'verbose_name_plural': 'Post tags',
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.post', verbose_name='Comment on post'),
        ),
    ]
