# Generated by Django 4.0.4 on 2022-05-07 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_comment_parent_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reaction',
            name='author_ip',
        ),
    ]
